export const ADD_PLACE_NAME = 'ADD_PLACE_NAME'
export const ADD_BUTTON = 'ADD_BUTTON'
export const SELECT_PLACE = 'SELECT_PLACE'
export const UNSELECT_PLACE = 'UNSELECT_PLACE'
export const DELETE_PLACE = 'DELETE_PLACE'

